
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yonlkixpgeiiqiexengg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvbmxraXhwZ2VpaXFpZXhlbmdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2ODQ5MDcsImV4cCI6MjA1NzI2MDkwN30.PAj_4trbj-y37eHFC7yVPI7oYcUeWwhwo2iGadoI5oY";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper functions for authentication with Google
export const signInWithGoogle = async () => {
  const { data, error } = await supabase.auth.signInWithOAuth({
    provider: 'google',
    options: {
      redirectTo: `${window.location.origin}/`
    }
  });
  
  return { data, error };
};

// Helper to upload avatar images
export const uploadAvatar = async (userId: string, file: File) => {
  try {
    // First check if the avatars bucket exists
    const { data: buckets } = await supabase.storage.listBuckets();
    const avatarBucketExists = buckets?.some(bucket => bucket.name === 'avatars');
    
    // If bucket doesn't exist, create it
    if (!avatarBucketExists) {
      await supabase.storage.createBucket('avatars', {
        public: true
      });
      console.log('Created avatars bucket');
    }
    
    const fileExt = file.name.split('.').pop();
    const filePath = `${userId}/avatar.${fileExt}`;
    
    // Upload the file
    const { error: uploadError } = await supabase.storage
      .from('avatars')
      .upload(filePath, file, { upsert: true });
      
    if (uploadError) {
      console.error('Error uploading avatar:', uploadError);
      throw uploadError;
    }
    
    // Get the public URL
    const { data } = supabase.storage.from('avatars').getPublicUrl(filePath);
    
    if (!data.publicUrl) {
      throw new Error('Failed to get public URL for avatar');
    }
    
    return data.publicUrl;
  } catch (error) {
    console.error('Avatar upload failed:', error);
    throw error;
  }
};

// Function to ensure avatars bucket exists
export const ensureAvatarsBucketExists = async () => {
  try {
    const { data: buckets } = await supabase.storage.listBuckets();
    const avatarBucketExists = buckets?.some(bucket => bucket.name === 'avatars');
    
    if (!avatarBucketExists) {
      const { error } = await supabase.storage.createBucket('avatars', {
        public: true
      });
      
      if (error) {
        console.error('Error creating avatars bucket:', error);
        return;
      }
      
      console.log('Created avatars bucket');
      
      // Create a policy to allow public access to avatars
      await supabase.storage.from('avatars').createSignedUrl('test.txt', 60);
    } else {
      console.log('Avatars bucket exists');
    }
  } catch (error) {
    console.error('Error ensuring avatars bucket exists:', error);
  }
};

// Call this function when the app starts
ensureAvatarsBucketExists();
