
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yonlkixpgeiiqiexengg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvbmxraXhwZ2VpaXFpZXhlbmdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2ODQ5MDcsImV4cCI6MjA1NzI2MDkwN30.PAj_4trbj-y37eHFC7yVPI7oYcUeWwhwo2iGadoI5oY";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Re-export authentication helpers from separate file
export { 
  signInWithGoogle,
  signInWithEmail,
  signOut,
  resetPassword
} from './auth';

// Re-export storage helpers from separate file
export {
  uploadAvatar,
  ensureAvatarsBucketExists
} from './storage';

// Re-export historical events helpers
export {
  fetchAllHistoricalEvents,
  fetchRandomHistoricalEvents,
  hasHistoricalEvents
} from './events';

// Initialize buckets on app start
import { ensureAvatarsBucketExists } from './storage';
ensureAvatarsBucketExists();
